### ISSUE TITLE
where can I find the "C:/Users/Emma/wsl/corona/Projects/Swiss-Wengen/data/metadata.tsv" file?

### ISSUE THREAD

**Issue by liamxg** [emmahodcroft/Intros_CH_AlphaDelta#2]
@emmahodcroft

**Comment by emmahodcroft** [comment]
Hi @liamxg I'm afraid the original data files cannot be shared due to the Terms of Use from GISAID. When the paper comes out there will be links to the EPI_ISL lists of the sequences used, from which one could create the meatdata.tsv and sequence alignment files that can be put into the code.

**Comment by liamxg** [comment]
@emmahodcroft any updates new about your paper?
